variables:
  REDHAWK_VERSION: '2.2.3'
stages:
  - test
image:
  name: geontech/redhawk-development:${REDHAWK_VERSION}
  entrypoint: [ '/bin/bash', '-lc' ]
test:
  stage: test
  before_script:
    - 'yum update -y'
    - 'yum install -y epel-release' 
    - 'yum groupinstall -y "Development Tools" "Development Libraries"'
    - 'yum install -y make automake gcc gcc-c++'
    - 'yum install -y git cmake3 boost-devel gnuplot'
    - 'yum install -y libusb*'
    - 'yum install -y sqlite sqlite-devel'
    - 'yum install -y bzip2'
    - 'makedir -p ~/bin/ && cd ~/bin/'
    - 'yum install -y gtk2-devel'
    - 'wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2'
    - 'tar -xf wxWidgets-3.1.0.tar.bz2'
    - 'cd wxWidgets-3.1.0/'
    - 'mkdir -p ~/bin/wxWidgets-staticlib'
    - './autogen.sh'
    - './configure --with-opengl --disable-shared --enable-monolithic --with-libjpeg --with-libtiff --with-libpng --with-zlib --disable-sdltest --enable-unicode --enable-display --enable-propgrid --disable-webkit --disable-webview --disable-webviewwebkit --prefix=`echo ~/bin/wxWidgets-staticlib` CXXFLAGS="-std=c++0x"'
    - 'make -j4'
    - 'make install'
    - 'cd /tmp'
    - 'git clone https://github.com/myriadrf/LimeSuite'
    - 'cd LimeSuite'
    - 'git checkout stable'
    - 'mkdir builddir && cd builddir'
    - 'cmake3 .. -DENABLE_GUI=OFF -DENABLE_API_DOXYGEN=ON -DwxWidgets_USE_STATIC:BOOL=ON -DwxWidgets_CONFIG_EXECUTABLE:FILEPATH=~/bin/wxWidgets-staticlib/bin/wx-config'
    - 'make -j4'
    - 'sudo make install'
    - 'sudo ldconfig'
    - 'cd ../udev-rules'
    - 'sudo ./install.sh'

  script:
    - 'LimeUtil --info'
    - 'redhawk-codegen --frontend ${CI_PROJECT_NAME}.spd.xml'
    - './build.sh'
    - './build.sh install'
