variables:
  REDHAWK_VERSION: '2.2.3'
stages:
  - test
image:
  name: geontech/redhawk-development:${REDHAWK_VERSION}
  entrypoint: [ '/bin/bash', '-lc' ]
test:
  stage: test
  before_script:
    - 'yum update -y'
    - 'yum install -y epel-release' 
    - 'yum install -y cmake3 boost-devel gnuplot'
    - 'yum install libusb* -y'
    - 'yum install sqlite sqlite-devel -y'
    - 'makedir -p ~/bin/ && cd ~/bin/'
    - 'wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2'
    - 'tar -xf wxWidgets-3.1.0.tar.bz2'
    - 'cd wxWidgets-3.1.0/'
    - 'mkdir -p ~/bin/wxWidgets-staticlib'
    - './autogen.sh'
    - './configure --with-opengl --disable-shared --enable-monolithic --with-libjpeg --with-libtiff --with-libpng --with-zlib --disable-sdltest --enable-unicode --enable-display --enable-propgrid --disable-webkit --disable-webview --disable-webviewwebkit --prefix=`echo ~/bin/wxWidgets-staticlib` CXXFLAGS="-std=c++0x"'
    - 'make -j4'
    - 'make install'
  script:
    - 'redhawk-codegen --frontend ${CI_PROJECT_NAME}.spd.xml'
    - './build.sh'
    - './build.sh install'
